<?php
// views/availability/index.php - Availability management view
$page_title = "Car Availability";
include __DIR__ . '/../layouts/header.php';
?>

<div class="dashboard-container">
    <?php include __DIR__ . '/../layouts/sidebar.php'; ?>
    
    <main class="main-content">
        <div class="header">
            <h1 class="page-title">Car Availability Management</h1>
            <div class="d-flex gap-2">
                <button class="btn btn-success" onclick="showBulkUpdateModal()">
                    <i class="fas fa-calendar-plus"></i> Bulk Update
                </button>
            </div>
        </div>

        <!-- Alert Messages -->
        <?php include __DIR__ . '/../layouts/alerts.php'; ?>

        <!-- Car Selection -->
        <div class="card mb-4">
            <div class="card-body">
                <div class="form-group mb-0">
                    <label class="form-label">Select Car to Manage Availability:</label>
                    <select class="form-control" id="car-select" style="max-width: 400px;">
                        <option value="">Select a car...</option>
                        <?php foreach ($cars as $car): ?>
                            <option value="<?php echo $car['id']; ?>" 
                                    <?php echo ($selected_car == $car['id']) ? 'selected' : ''; ?>>
                                <?php echo htmlspecialchars($car['make'] . ' ' . $car['model'] . ' (' . $car['year'] . ') - ' . $car['license_plate']); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>

        <?php if ($selected_car): ?>
            <!-- Calendar View -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Availability Calendar</h3>
                    <div class="d-flex gap-2">
                        <button class="btn btn-outline btn-sm" onclick="previousMonth()">
                            <i class="fas fa-chevron-left"></i> Previous
                        </button>
                        <span id="current-month" class="btn btn-outline btn-sm" style="cursor: default;"></span>
                        <button class="btn btn-outline btn-sm" onclick="nextMonth()">
                            Next <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <!-- Legend -->
                    <div class="d-flex gap-4 mb-3" style="font-size: 0.875rem;">
                        <div class="d-flex items-center gap-1">
                            <div style="width: 16px; height: 16px; background: #10b981; border-radius: 3px;"></div>
                            <span>Available</span>
                        </div>
                        <div class="d-flex items-center gap-1">
                            <div style="width: 16px; height: 16px; background: #f59e0b; border-radius: 3px;"></div>
                            <span>Booked</span>
                        </div>
                        <div class="d-flex items-center gap-1">
                            <div style="width: 16px; height: 16px; background: #ef4444; border-radius: 3px;"></div>
                            <span>Blocked</span>
                        </div>
                        <div class="d-flex items-center gap-1">
                            <div style="width: 16px; height: 16px; background: #6b7280; border-radius: 3px;"></div>
                            <span>Past Date</span>
                        </div>
                    </div>

                    <!-- Calendar -->
                    <div class="calendar" id="availability-calendar">
                        <div class="calendar-grid">
                            <!-- Day headers -->
                            <div class="calendar-day-header">Sun</div>
                            <div class="calendar-day-header">Mon</div>
                            <div class="calendar-day-header">Tue</div>
                            <div class="calendar-day-header">Wed</div>
                            <div class="calendar-day-header">Thu</div>
                            <div class="calendar-day-header">Fri</div>
                            <div class="calendar-day-header">Sat</div>
                            
                            <!-- Calendar days will be generated by JavaScript -->
                        </div>
                    </div>

                    <!-- Instructions -->
                    <div class="mt-3" style="font-size: 0.875rem; color: var(--text-muted);">
                        <strong>Instructions:</strong>
                        <ul style="margin: 0.5rem 0 0 1.5rem;">
                            <li>Click on any available date to block it</li>
                            <li>Click on any blocked date to make it available</li>
                            <li>Booked dates cannot be changed</li>
                            <li>Past dates are shown in gray</li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Blocked Dates List -->
            <div class="card mt-4">
                <div class="card-header">
                    <h3 class="card-title">Blocked Dates</h3>
                </div>
                <div class="card-body">
                    <div id="blocked-dates-list">
                        <?php if (empty($blocked_dates)): ?>
                            <p class="text-muted text-center">No blocked dates for this car.</p>
                        <?php else: ?>
                            <div class="table-container">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Reason</th>
                                            <th>Type</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($blocked_dates as $blocked): ?>
                                            <tr>
                                                <td><?php echo formatDate($blocked['date']); ?></td>
                                                <td><?php echo htmlspecialchars($blocked['reason']); ?></td>
                                                <td>
                                                    <span class="badge badge-<?php echo $blocked['type'] === 'booking' ? 'warning' : 'danger'; ?>">
                                                        <?php echo ucfirst($blocked['type']); ?>
                                                    </span>
                                                </td>
                                                <td>
                                                    <?php if ($blocked['type'] === 'manual'): ?>
                                                        <button class="btn btn-sm btn-success" 
                                                                onclick="removeBlockedDate('<?php echo $blocked['date']; ?>')">
                                                            <i class="fas fa-check"></i> Make Available
                                                        </button>
                                                    <?php else: ?>
                                                        <span class="text-muted">Cannot modify</span>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <!-- No Car Selected -->
            <div class="card">
                <div class="card-body text-center" style="padding: 3rem;">
                    <i class="fas fa-calendar-alt" style="font-size: 4rem; color: var(--text-muted); margin-bottom: 1rem;"></i>
                    <h3 style="color: var(--text-muted); margin-bottom: 1rem;">Select a Car</h3>
                    <p class="text-muted">Choose a car from the dropdown above to manage its availability.</p>
                </div>
            </div>
        <?php endif; ?>
    </main>
</div>

<!-- Bulk Update Modal -->
<div id="bulk-update-modal" class="modal" style="display: none;">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Bulk Update Availability</h3>
            <button class="modal-close">&times;</button>
        </div>
        <div class="modal-body">
            <form id="bulk-update-form">
                <div class="form-group">
                    <label class="form-label">Car</label>
                    <select name="car_id" class="form-control" required>
                        <option value="">Select a car...</option>
                        <?php foreach ($cars as $car): ?>
                            <option value="<?php echo $car['id']; ?>">
                                <?php echo htmlspecialchars($car['make'] . ' ' . $car['model'] . ' (' . $car['year'] . ') - ' . $car['license_plate']); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Date Range</label>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
                        <input type="date" name="start_date" class="form-control" required>
                        <input type="date" name="end_date" class="form-control" required>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Action</label>
                    <select name="action" class="form-control" required>
                        <option value="block">Block Dates</option>
                        <option value="unblock">Make Available</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Reason (for blocking)</label>
                    <input type="text" name="reason" class="form-control" placeholder="e.g., Maintenance, Personal use">
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline" data-modal-close>Cancel</button>
            <button type="submit" form="bulk-update-form" class="btn btn-primary">Update Availability</button>
        </div>
    </div>
</div>

<script>
let currentMonth = new Date();
let selectedCarId = <?php echo $selected_car ? $selected_car : 'null'; ?>;
let blockedDates = <?php echo json_encode($blocked_dates); ?>;

document.addEventListener('DOMContentLoaded', function() {
    // Set minimum date to today
    const today = new Date().toISOString().split('T')[0];
    document.querySelectorAll('input[type="date"]').forEach(input => {
        input.min = today;
    });
    
    if (selectedCarId) {
        renderCalendar();
    }
    
    // Car selection change
    document.getElementById('car-select').addEventListener('change', function() {
        if (this.value) {
            window.location.href = `?page=availability&car_id=${this.value}`;
        }
    });
});

function renderCalendar() {
    const calendar = document.getElementById('availability-calendar');
    const monthHeader = document.getElementById('current-month');
    
    // Update month header
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                       'July', 'August', 'September', 'October', 'November', 'December'];
    monthHeader.textContent = monthNames[currentMonth.getMonth()] + ' ' + currentMonth.getFullYear();
    
    // Clear existing calendar days (keep headers)
    const existingDays = calendar.querySelectorAll('.calendar-day');
    existingDays.forEach(day => day.remove());
    
    // Get first day of month and number of days
    const firstDay = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), 1);
    const lastDay = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 0);
    const startDate = firstDay.getDay(); // Day of week (0 = Sunday)
    const daysInMonth = lastDay.getDate();
    
    const today = new Date();
    const grid = calendar.querySelector('.calendar-grid');
    
    // Add empty cells for days before month starts
    for (let i = 0; i < startDate; i++) {
        const emptyDay = document.createElement('div');
        emptyDay.className = 'calendar-day';
        emptyDay.style.opacity = '0';
        grid.appendChild(emptyDay);
    }
    
    // Add days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const dayElement = document.createElement('div');
        dayElement.className = 'calendar-day';
        dayElement.textContent = day;
        
        const currentDate = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day);
        const dateString = currentDate.toISOString().split('T')[0];
        dayElement.setAttribute('data-date', dateString);
        
        // Check if date is in the past
        if (currentDate < today) {
            dayElement.classList.add('past-date');
            dayElement.style.background = '#6b7280';
            dayElement.style.color = 'white';
            dayElement.style.cursor = 'not-allowed';
        } else {
            // Check if date is blocked
            const blockedDate = blockedDates.find(d => d.date === dateString);
            if (blockedDate) {
                if (blockedDate.type === 'booking') {
                    dayElement.classList.add('booked');
                    dayElement.style.background = '#f59e0b';
                    dayElement.style.color = 'white';
                    dayElement.title = 'Booked - ' + blockedDate.reason;
                    dayElement.style.cursor = 'not-allowed';
                } else {
                    dayElement.classList.add('blocked');
                    dayElement.style.background = '#ef4444';
                    dayElement.style.color = 'white';
                    dayElement.title = 'Blocked - ' + blockedDate.reason;
                    dayElement.addEventListener('click', () => toggleDateAvailability(dateString, true));
                }
            } else {
                dayElement.classList.add('available');
                dayElement.style.background = '#10b981';
                dayElement.style.color = 'white';
                dayElement.title = 'Available';
                dayElement.addEventListener('click', () => toggleDateAvailability(dateString, false));
            }
        }
        
        // Highlight today
        if (currentDate.toDateString() === today.toDateString()) {
            dayElement.style.border = '2px solid #4f46e5';
        }
        
        grid.appendChild(dayElement);
    }
}

function toggleDateAvailability(date, makeAvailable) {
    const reason = makeAvailable ? '' : prompt('Reason for blocking this date (optional):') || 'Manually blocked';
    
    if (!makeAvailable && reason === null) return; // User cancelled
    
    fetch('controllers/AjaxController.php', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: `action=set_availability&car_id=${selectedCarId}&date=${date}&is_available=${makeAvailable}&reason=${encodeURIComponent(reason)}`
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            // Update blocked dates array
            if (makeAvailable) {
                blockedDates = blockedDates.filter(d => d.date !== date);
            } else {
                blockedDates.push({date: date, reason: reason, type: 'manual'});
            }
            
            // Re-render calendar
            renderCalendar();
            
            // Update blocked dates list
            location.reload(); // Simple reload for now
            
            showAlert('success', data.message);
        } else {
            showAlert('error', data.message);
        }
    })
    .catch(error => {
        console.error('Error:', error);
        showAlert('error', 'An error occurred. Please try again.');
    });
}

function removeBlockedDate(date) {
    if (confirm('Are you sure you want to make this date available?')) {
        toggleDateAvailability(date, true);
    }
}

function previousMonth() {
    currentMonth.setMonth(currentMonth.getMonth() - 1);
    renderCalendar();
}

function nextMonth() {
    currentMonth.setMonth(currentMonth.getMonth() + 1);
    renderCalendar();
}

function showBulkUpdateModal() {
    showModal('bulk-update-modal');
}

// Bulk update form handling
document.getElementById('bulk-update-form').addEventListener('submit', function(e) {
    e.preventDefault();
    
    const formData = new FormData(this);
    const submitBtn = this.querySelector('button[type="submit"]');
    
    submitBtn.disabled = true;
    submitBtn.textContent = 'Updating...';
    
    // Here you would send the bulk update request
    // For now, we'll just show a success message
    setTimeout(() => {
        hideModal();
        showAlert('success', 'Availability updated successfully!');
        location.reload();
    }, 1000);
});
</script>

<style>
.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: var(--border-color);
    border: 1px solid var(--border-color);
}

.calendar-day-header {
    background: var(--secondary-color);
    padding: 0.75rem;
    text-align: center;
    font-weight: 600;
    font-size: 0.875rem;
}

.calendar-day {
    background: white;
    padding: 0.75rem;
    text-align: center;
    min-height: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.2s ease;
    position: relative;
}

.calendar-day:hover:not(.past-date):not(.booked) {
    transform: scale(1.05);
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.past-date {
    opacity: 0.5;
}

@media (max-width: 768px) {
    .calendar-day {
        min-height: 40px;
        padding: 0.5rem;
        font-size: 0.875rem;
    }
    
    .calendar-day-header {
        padding: 0.5rem;
        font-size: 0.75rem;
    }
}
</style>

<?php include __DIR__ . '/../layouts/footer.php'; ?>